### ISSUE TITLE
models/appconf can't get settings.MEDIA_URL and MEDIA_ROOT

### ISSUE THREAD

**Issue by bclermont** [jezdez/django-staticfiles#15]
and probably more:

``` python
www-data@sologroup-01:/usr/local/src/sologroup.gs$ bin/django shell
Traceback (most recent call last):
  File "bin/django", line 18, in <module>
    djangorecipe.manage.main('sologroup.production')
  File "/usr/local/src/sologroup.gs/eggs/djangorecipe-0.99-py2.6.egg/djangorecipe/manage.py", line 16, in main
    management.execute_manager(mod)
  File "/usr/local/src/sologroup.gs/eggs/Django-1.2.5-py2.6.egg/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/usr/local/src/sologroup.gs/eggs/Django-1.2.5-py2.6.egg/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/src/sologroup.gs/eggs/Django-1.2.5-py2.6.egg/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/src/sologroup.gs/eggs/Django-1.2.5-py2.6.egg/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/usr/local/src/sologroup.gs/eggs/Django-1.2.5-py2.6.egg/django/core/management/base.py", line 351, in handle
    return self.handle_noargs(**options)
  File "/usr/local/src/sologroup.gs/eggs/Django-1.2.5-py2.6.egg/django/core/management/commands/shell.py", line 18, in handle_noargs
    loaded_models = get_models()
  File "/usr/local/src/sologroup.gs/eggs/Django-1.2.5-py2.6.egg/django/db/models/loading.py", line 167, in get_models
    self._populate()
  File "/usr/local/src/sologroup.gs/eggs/Django-1.2.5-py2.6.egg/django/db/models/loading.py", line 61, in _populate
    self.load_app(app_name, True)
  File "/usr/local/src/sologroup.gs/eggs/Django-1.2.5-py2.6.egg/django/db/models/loading.py", line 78, in load_app
    models = import_module('.models', app_name)
  File "/usr/local/src/sologroup.gs/eggs/Django-1.2.5-py2.6.egg/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/local/src/sologroup.gs/lib/python2.6/site-packages/staticfiles/models.py", line 10, in <module>
    class StaticFilesConf(AppConf):
  File "/usr/local/src/sologroup.gs/lib/python2.6/site-packages/appconf.py", line 70, in __new__
    new_class._configure()
  File "/usr/local/src/sologroup.gs/lib/python2.6/site-packages/appconf.py", line 91, in _configure
    value = callback(value)
  File "/usr/local/src/sologroup.gs/lib/python2.6/site-packages/staticfiles/models.py", line 50, in configure_url
    if url == self.MEDIA_URL:
  File "/usr/local/src/sologroup.gs/lib/python2.6/site-packages/appconf.py", line 145, in __getattr__
    (name, self._meta.holder_path))
AttributeError: MEDIA_URL not found. Use 'django.conf.settings' instead.
```

if I replace self.MEDIA_URL to settings.MEDIA_URL it work.

**Comment by jezdez** [comment]
Ah, thanks, bug fix forthcoming.

**Comment by jezdez** [comment]
1.1.2 was also released.
